#!/bin/bash

echo "Setting up workspace folder: $WORKSPACE_FOLDER"
cd $WORKSPACE_FOLDER
rm -rf $WORKSPACE_FOLDER/.vscode/*
cp "$HOME/dotfiles/.vscode/extensions.json" $WORKSPACE_FOLDER/.vscode/
cp "$HOME/dotfiles/.vscode/settings.json" $WORKSPACE_FOLDER/.vscode/
mkdir "$HOME/.config"
ln -s "$HOME/dotfiles/.config/phpactor" "$HOME/.config/phpactor"

if command -v code &> /dev/null; then
    echo "Installing recommended extensions from extensions.json"
    for extension in $(grep -oP '"\K[\w-]+\.[\w-]+(?=")' "$WORKSPACE_FOLDER/.vscode/extensions.json"); do
        code --install-extension "$extension" --force
    done
else
    echo "'code' command not found, skipping automatic extension installation"
fi
