#!/bin/bash

cd $WORKSPACE_FOLDER
rm -rf .vscode/*
cp "$HOME/dotfiles/.vscode/extensions.json" .vscode/
cp "$HOME/dotfiles/.vscode/settings.json" .vscode/
mkdir "$HOME/.config"
ln -s "$HOME/dotfiles/.config/phpactor" "$HOME/.config/phpactor"

composer global require friendsofphp/php-cs-fixer
